# Generated by Django 5.0.4 on 2024-05-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_course_grade_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['user__username']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
