# Generated by Django 5.0.4 on 2024-05-08 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='school.college', verbose_name='所属学院'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='school.course'),
        ),
    ]
