# Generated by Django 5.0.4 on 2024-05-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identified_check',
            field=models.CharField(choices=[('S', '学生'), ('A', '管理员'), ('T', '教师')], default='S', max_length=1),
        ),
    ]
